import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.io.IOException;

public class Main
{
	private JPanel test;

	public static void main(String[] args)
	{
		Main main = new Main();

		// menuBar colors
		Color menuBarBackground = new Color(52, 52, 53);
		Color menuBarBorderColor = new Color(60, 60, 61);
		Color menuTextColor = new Color(231, 231, 231);

		// menuBar fonts
		Font menuBarFont = null;
		try
		{
			String robotoPath = "src/fonts/Roboto-Regular.ttf";

			Font robotoRegular = Font.createFont(Font.TRUETYPE_FONT, new File(robotoPath));

			GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
			ge.registerFont(robotoRegular);

			menuBarFont = robotoRegular.deriveFont(Font.PLAIN, 13);
		} catch (IOException | FontFormatException exception)
		{
			exception.printStackTrace();
		}

		// JMenuBar initialization
		JMenuBar menuBar = new JMenuBar();

		menuBar.setBackground(menuBarBackground);
		menuBar.setBorder(BorderFactory.createLineBorder(menuBarBorderColor));

		// JMenu initializations
		UIManager.put("Menu.foreground", menuTextColor);
		UIManager.put("Menu.font", menuBarFont);

		UIManager.put("MenuItem.background", menuBarBackground);
		UIManager.put("MenuItem.font", menuBarFont);
		UIManager.put("MenuItem.border", BorderFactory.createLineBorder(menuBarBorderColor));
		UIManager.put("MenuItem.foreground", menuTextColor);

		UIManager.put("PopupMenu.border", BorderFactory.createLineBorder(menuBarBorderColor));

		JMenu register = new JMenu("Register");
		JMenu userMenu = new JMenu("User");
		JMenu adminMenu = new JMenu("Admin");

		// Add menus to menuBar
		menuBar.add(register);
		menuBar.add(userMenu);
		menuBar.add(adminMenu);

		// User Log-in menu
		JMenuItem userLogIn = new JMenuItem("Log-in User");

		// Admin Log-in menu
		JMenuItem adminLogIn = new JMenuItem("Admin Log-in");

		// Add log-in submenus
		userMenu.add(userLogIn);
		adminMenu.add(adminLogIn);

		// Sell Menu & Submenus
		JMenu sellMenu = new JMenu("Sell Menu");

		// JFrame initialization
		JFrame frame = new JFrame("Jojo's Bizarre Shopping App");

		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.setSize(1280, 720);
		frame.setContentPane(main.test);
		frame.setJMenuBar(menuBar);
		frame.setVisible(true);
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$()
	{
		test = new JPanel();
		test.setLayout(new CardLayout(0, 0));
		test.setBackground(new Color(-14145489));
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$()
	{
		return test;
	}

}